### Test GET request
GET http://localhost:8000/
Accept: application/json

### Test POST request with image upload
POST http://localhost:8000/img-to-vector
Accept: application/json
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary

< /home/shah/Pictures/Vega_RD_RG_A2_V1.webp
